package com.plotter.gui;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Timer;
import java.util.TimerTask;

import javax.swing.JFrame;
import javax.swing.JSplitPane;

import com.plotter.algorithms.LibkokiUtils;
import com.plotter.algorithms.LibkokiUtils.MarkerInfo;
import com.plotter.algorithms.ShapeData;
import com.plotter.data.Database;
import com.plotter.data.DatabaseMultipoly;
import com.plotter.xmlcorrection.XMLCorrectionData;

public class XMLCorrection extends JFrame {

	private final File xmlFileLocation;
	private final Database database;
	private final CorrectionPanel panel;
	private final PropertiesPanel properties;
	private XMLCorrectionData data;
	private JSplitPane splitPane;
	
	public XMLCorrection(final File selectedFile, final BufferedImage image, final Database database) {
		this.xmlFileLocation = new File(selectedFile.getAbsolutePath().substring(0, selectedFile.getAbsolutePath().length() - 4) + "Data.xml");
		this.database = database;
		List<MarkerInfo> markers = new ArrayList<>();
		Set<DatabaseMultipoly> allocatedShapes = new HashSet<>();
		Set<MarkerInfo> allocatedMarkers = new HashSet<>();
		List<ShapeData> shapeData = new ArrayList<>();
		Map<ShapeData, DatabaseMultipoly> shapeDataMapping = new HashMap<>();
		
		BufferedImage gImage = new BufferedImage(image.getWidth(), image.getHeight(), BufferedImage.TYPE_INT_ARGB);
		
		LibkokiUtils.getShapes(selectedFile, (Graphics2D)gImage.getGraphics(), database, markers, allocatedShapes, allocatedMarkers, shapeData, shapeDataMapping);
		
		// Init with the data generated by libkoki
		this.data = new XMLCorrectionData(shapeData, shapeDataMapping, database);
		
		this.properties = new PropertiesPanel(data);
		this.data.loadVariables(properties);
		
		this.setTitle("Correction Screen");
		
		this.panel = new CorrectionPanel(data, image);
		this.panel.init();
		
		splitPane = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, panel, properties);
		this.add(splitPane);
		
		splitPane.setDividerLocation(0.8);
		splitPane.setResizeWeight(0.8);
		
		//Provide minimum sizes for the two components in the split pane
		Dimension minimumSize = new Dimension(100, 50);
		panel.setMinimumSize(minimumSize);
		properties.setMinimumSize(minimumSize);
		
		Timer paintTimer = new Timer();
		paintTimer.scheduleAtFixedRate(new TimerTask() {
			
			@Override
			public void run() {
				XMLCorrection.this.repaint();
				if(properties.update())
					data.updateShapes();
			}
		}, 0, 16);
		
		this.setSize(800, 600);
	}
	
	@Override
	public void paint(Graphics g) {
		super.paint(g);
		this.panel.repaint();
	}
	
}
